const ytdl = require('ytdl-core');
const PlaylistHandler = require('../../utils/playlistHandler.js'); // Adjust path as needed

module.exports = {
  name: 'play',
  description: 'Play a song from YouTube or Spotify',
  async execute(message, args, client) {
    const voiceChannel = message.member.voice.channel;
    if (!voiceChannel) {
      return message.channel.send('❌ You need to be in a voice channel to play music!');
    }

    // Check bot permissions
    const permissions = voiceChannel.permissionsFor(message.client.user);
    if (!permissions.has('Connect') || !permissions.has('Speak')) {
      return message.channel.send('❌ I need permissions to join and speak in your voice channel!');
    }

    // Track the session owner
    if (!client.voiceSessionOwner.has(message.guild.id)) {
      client.voiceSessionOwner.set(message.guild.id, message.author.id);
    }

    if (!args.length) {
      return message.channel.send('❌ Please provide a song name or URL.\n💡 **Examples:**\n• `!play Never Gonna Give You Up`\n• `!play https://www.youtube.com/watch?v=dQw4w9WgXcQ`\n• `!play https://open.spotify.com/track/4PTG4QX7Qyb6Z7HLYHZMeQ`');
    }

    let query = args.join(' ');
    let isPlaylist = false;
    let playlistType = '';

    // Enhanced URL processing and validation
    try {
      if (this.isValidUrl(query)) {
        const processedQuery = this.processUrl(query);
        query = processedQuery.url;
        isPlaylist = processedQuery.isPlaylist;
        playlistType = processedQuery.playlistType;
      }
      
    } catch (error) {
      console.log('URL processing error:', error.message);
      
      // Handle auto-generated playlists by attempting to extract all songs
      if (error.message.includes('Auto-generated playlists are not supported')) {
        try {
          // Try to extract all songs from the auto-generated playlist
          const playlistHandler = client.playlistHandler;
          message.channel.send('🤖 **Auto-generated playlist detected!** Attempting to extract all songs...\n⏳ This might take a moment...');
          
          const result = await playlistHandler.handleAutoGeneratedPlaylist(voiceChannel, query, message.channel, message.member);
          if (result.success) {
            return; // Successfully handled, exit the function
          }
          
          // If extraction fails, fall back to single video
          const urlObj = new URL(query);
          const videoId = urlObj.searchParams.get('v');
          if (videoId) {
            query = `https://www.youtube.com/watch?v=${videoId}`;
            isPlaylist = false;
            playlistType = '';
            console.log('Fallback: Extracted single video from auto-generated playlist:', query);
            message.channel.send('⚠️ **Could not extract full playlist.** Playing the current video instead.');
          }
        } catch (extractError) {
          console.log('Auto-generated playlist extraction failed:', extractError.message);
          // Continue with original query
        }
      }
    }

    console.log('Voice channel:', voiceChannel.name);
    console.log('Playing query:', query);
    console.log('Is playlist:', isPlaylist, playlistType ? `(${playlistType})` : '');
    
    // Send initial message with better feedback
    const loadingEmojis = ['🔍', '🎵', '🎶', '🎧'];
    const randomEmoji = loadingEmojis[Math.floor(Math.random() * loadingEmojis.length)];
    
    let searchMessage;
    if (isPlaylist) {
      searchMessage = await message.channel.send(`${randomEmoji} Loading playlist... This might take a moment for large playlists.`);
    } else {
      searchMessage = await message.channel.send(`${randomEmoji} Searching: \`${query.length > 50 ? query.substring(0, 50) + '...' : query}\``);
    }
    
    try {
      // Initialize playlist handler
      const playlistHandler = client.playlistHandler;

      // Skip playlist handler if it's a Spotify playlist
      if (playlistType === 'spotify-playlist') {
        console.log('🎧 Detected Spotify playlist. Letting DisTube handle it directly.');
        isPlaylist = false; // prevent handler from treating as playlist
      }

      // Handle playlists with advanced fallback methods
      if (isPlaylist && playlistHandler.isPlaylistSupported(query)) {
        try {
          const result = await playlistHandler.handlePlaylist(voiceChannel, query, message.channel, message.member);
          searchMessage.edit(`✅ Playlist loaded using ${result.method} method! 🎉${result.stats ? `\n📊 Added: ${result.stats.successCount}/${result.stats.total} songs` : ''}`);
          return;
        } catch (playlistError) {
          console.log('All playlist methods failed, trying as single video...');
          // Fall through to try as single video
        }
      }

      // Regular play method (single songs or when playlist fails)
      const playPromise = client.distube.play(voiceChannel, query, {
        textChannel: message.channel,
        member: message.member
      });

      // Set timeout for regular play
      const timeoutPromise = new Promise((_, reject) => {
        setTimeout(() => reject(new Error('Timeout: Request took too long')), 60000);
      });

      await Promise.race([playPromise, timeoutPromise]);

      // Success message
      if (isPlaylist) {
        searchMessage.edit(`✅ Playlist loaded successfully! 🎉`);
      } else {
        searchMessage.edit(`✅ Found and added to queue! 🎵`);
      }
      
    } catch (error) {
      console.error('DisTube Play Error:', error);
      
      const errorMessage = this.getErrorMessage(error, isPlaylist, playlistType, query);
      searchMessage.edit(errorMessage);
    }
  },

  // Helper function to check if string is a valid URL
  isValidUrl(string) {
    try {
      new URL(string);
      return true;
    } catch (_) {
      return false;
    }
  },

  // Enhanced URL processing function
  processUrl(url) {
    const urlObj = new URL(url);
    let isPlaylist = false;
    let playlistType = '';

    // Spotify playlist handling
    if (urlObj.hostname.includes('spotify.com') && urlObj.pathname.startsWith('/playlist/')) {
      return {
        url: urlObj.toString(),
        isPlaylist: false, // treat as single track, let SpotifyPlugin handle it
        playlistType: 'spotify-playlist'
      };
    }
    
    // YouTube Music to YouTube conversion
    if (urlObj.hostname.includes('music.youtube.com')) {
      urlObj.hostname = 'www.youtube.com';
    }

    // Detect playlist types
    if (urlObj.searchParams.has('list')) {
      isPlaylist = true;
      const listId = urlObj.searchParams.get('list');
      
      // Identify problematic playlist types
      if (listId.startsWith('RDEM') || listId.startsWith('RDMM')) {
        playlistType = 'auto-generated';
        throw new Error('Auto-generated playlists are not supported');
      } else if (listId.startsWith('RD')) {
        playlistType = 'radio';
        throw new Error('Radio playlists are not supported');
      } else if (listId.startsWith('UU') || listId.startsWith('UULF')) {
        playlistType = 'channel-uploads';
      } else if (listId.startsWith('PL')) {
        playlistType = 'user-playlist';
      } else {
        playlistType = 'unknown';
      }
    }

    // Clean up problematic parameters
    const problematicParams = [
      'start_radio', 'si', 'feature', 'app', 'playnext', 'index', 
      'start_radio_session', 'radio', 'autoplay'
    ];
    
    problematicParams.forEach(param => {
      if (urlObj.searchParams.has(param)) {
        urlObj.searchParams.delete(param);
      }
    });

    // For playlists, create clean URL
    if (isPlaylist) {
      const listId = urlObj.searchParams.get('list');
      if (listId) {
        return {
          url: `https://www.youtube.com/playlist?list=${listId}`,
          isPlaylist: true,
          playlistType
        };
      }
    }

    return {
      url: urlObj.toString(),
      isPlaylist,
      playlistType
    };
  },

  // Enhanced error message function
  getErrorMessage(error, isPlaylist, playlistType, originalQuery) {
    let errorMessage = '❌ Failed to play content.';
    
    if (error.message) {
      const msg = error.message.toLowerCase();
      
      if (msg.includes('cannot read properties of undefined') || msg.includes('map')) {
        if (isPlaylist) {
          errorMessage = '❌ **Playlist format not supported**\n\n';
          if (playlistType === 'auto-generated') {
            errorMessage += '🤖 Auto-generated playlists (YouTube Music mixes) cannot be played.\n';
            errorMessage += '💡 **Try instead:**\n• Search for individual songs\n• Use a manually created playlist\n• Copy specific song titles from the mix';
          } else {
            errorMessage += '📋 This playlist format is not compatible.\n';
            errorMessage += '💡 **Try instead:**\n• Individual songs from the playlist\n• A different playlist format\n• Manual song requests';
          }
        } else {
          errorMessage = '❌ Could not process this content. Try a different search term or URL.';
        }
      } else if (msg.includes('unknown playlist')) {
        errorMessage = '❌ **Playlist not accessible**\n\n';
        errorMessage += '🔒 This playlist might be:\n• Private or unlisted\n• Region-restricted\n• Auto-generated (not supported)\n\n';
        errorMessage += '💡 **Try:** Individual songs or public playlists';
      } else if (msg.includes('timeout')) {
        errorMessage = '❌ **Request timed out**\n\n';
        if (isPlaylist) {
          errorMessage += '⏰ Large playlists can take time to load.\n💡 **Try:** Smaller playlists or individual songs';
        } else {
          errorMessage += '⏰ The request took too long.\n💡 **Try:** A different search term or check your connection';
        }
      } else if (msg.includes('sign in') || msg.includes('login')) {
        errorMessage = '❌ **Sign-in required**\n🔐 This content requires authentication and cannot be accessed.';
      } else if (msg.includes('private')) {
        errorMessage = '❌ **Private content**\n🔒 This video/playlist is private or has been removed.';
      } else if (msg.includes('age') || msg.includes('restricted')) {
        errorMessage = '❌ **Age-restricted content**\n🔞 This content cannot be played due to age restrictions.';
      } else if (msg.includes('not available') || msg.includes('blocked')) {
        errorMessage = '❌ **Content not available**\n🌍 This might be region-blocked or removed.';
      } else if (msg.includes('quota') || msg.includes('limit')) {
        errorMessage = '❌ **Service limit reached**\n⚠️ YouTube API quota exceeded. Try again later.';
      } else if (error.name === 'PlayError') {
        errorMessage = '❌ **Playback failed**\n\n💡 **Try:**\n';
        if (isPlaylist) {
          errorMessage += '• Individual songs from the playlist\n• A different playlist\n• Searching for specific tracks';
        } else {
          errorMessage += '• A different search term\n• Checking if the video exists\n• Using a direct YouTube URL';
        }
      } else {
        errorMessage = `❌ **Error:** ${error.message}`;
      }
    }
    
    // Add helpful tips based on the original query
    if (originalQuery.includes('music.youtube.com')) {
      errorMessage += '\n\n🎵 **YouTube Music Tip:** Try searching for the song name instead of using the Music URL.';
    } else if (originalQuery.includes('spotify.com')) {
      errorMessage += '\n\n🎧 **Spotify Tip:** Make sure the track is available on YouTube as well.';
    }
    
    return errorMessage;
  }
};